### ISSUE TITLE
Problems on Drupal 8.2.1

### ISSUE THREAD

**Issue by vegardjo** [larowlan/block_access#3]
Hi, I've been using this successfully on Drupal 8.1.9, but when updating to 8.2.1 I get the following error:

Fatal error: Call to a member function id() on null in [...]modules/custom/block_access/block_access.module on line 26

I've tried clearing caches + uniinstalling and reinstalling the module, but the error prevails

**Comment by ekes** [comment]
Think the pull request #5 will fix this one for you.
